FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:4bd7cb8abd091e6161490da1c3dd615532e537c62b8b98d6b2acd77e248ead62 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY jaeger jaeger
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger

RUN go build -C ./cmd/es-rollover -mod=mod -o ./jaeger -trimpath -ldflags "-s -w"


FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:c38cc770631788157f8ea989df65ff30359c9f8af3246fef244b32caed9d5862
WORKDIR /

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger/cmd/es-rollover/jaeger /usr/bin/jaeger

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL com.redhat.component="jaeger-es-rollover-container" \
      name="rhosdt/jaeger-es-rollover-rhel8" \
      summary="Jaeger ES rollover" \
      description="Index rollover for the distributed tracing system" \
      io.k8s.description="Index rollover for the distributed tracing system." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger ES rollover"
