FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:5b195cf0b8eb2262ce81334ee44066fdb5026022803f55bfe607be7d08d4fe43 as builder

USER root
WORKDIR /opt/bundle-build

# TODO use python3-ruamel-yaml-clib python3-ruamel-yaml once on RHEL9 which is easier to use
RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install -y python3 python3-pyyaml patch

RUN mkdir /licenses
COPY jaeger-operator/LICENSE /licenses/.

COPY bundle-patch .
COPY jaeger-operator/bundle/manifests manifests/
COPY jaeger-operator/bundle/metadata metadata/

RUN ls manifests -al
RUN ls metadata -al

# stage - registry.stage.redhat.io, prod - registry.redhat.io
ARG REGISTRY=registry.redhat.io

RUN ./update_bundle.sh && cat manifests/jaeger-operator.clusterserviceversion.yaml metadata/annotations.yaml

FROM scratch

WORKDIR /

COPY jaeger-operator/LICENSE /licenses/.

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=jaeger-product
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.29.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL release="1.65.0-2" \
      version="1.65.0-2" \
      com.redhat.openshift.versions=v4.12 \
      name="rhosdt/jaeger-operator-bundle" \
      distribution-scope="public" \
      description="Bundle for Jaeger operator" \
      io.k8s.description="Bundle for Jaeger operator." \
      # TODO check if this is correct
      com.redhat.component="rhosdt" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Operator Bundle" \
      url="https://github.com/jaegertracing/jaeger-operator" \
      vendor="Red Hat, Inc." \
      summary="Jaeger operator bundle" \
      maintainer="support@redhat.com"

# Copy files to locations specified by labels.
COPY --from=builder /opt/bundle-build/manifests /manifests/
COPY --from=builder /opt/bundle-build/metadata /metadata/
COPY jaeger-operator/bundle/tests/scorecard /tests/scorecard/

ARG USER_UID=1001
USER ${USER_UID}
