FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:0a070e4a8f2698b6aba3630a49eb995ff1b0a182d0c5fa264888acf9d535f384 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY jaeger jaeger
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/jaegertracing/jaeger/pkg/version" && \
    exportOrFail VERSION_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail GIT_LATEST_TAG=`set -e; git describe --abbrev=0 --tags` && \
    exportOrFail GIT_COMMIT_SHA=`git rev-parse HEAD` && \
    go build -C ./cmd/ingester -mod=mod -o ./jaeger -trimpath -ldflags "-s -w -X ${VERSION_PKG}.commitSHA=${GIT_COMMIT_SHA} -X ${VERSION_PKG}.latestVersion=${GIT_LATEST_TAG} -X ${VERSION_PKG}.date=${VERSION_DATE}"


FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:c38cc770631788157f8ea989df65ff30359c9f8af3246fef244b32caed9d5862
WORKDIR /

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger/cmd/ingester/jaeger /usr/bin/jaeger

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL com.redhat.component="jaeger-ingester-container" \
      name="rhosdt/jaeger-ingester-rhel8" \
      summary="Jaeger Ingester" \
      description="Ingester for the distributed tracing system" \
      io.k8s.description="Ingester for the distributed tracing system." \
      io.openshift.expose-services="14270:health-http,14271:metrics-http,4317:grpc,4318:http" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger ingester"
