FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:4bd7cb8abd091e6161490da1c3dd615532e537c62b8b98d6b2acd77e248ead62 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY jaeger-operator jaeger-operator
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger-operator/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger-operator

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/jaegertracing/jaeger-operator/pkg/version" && \
    exportOrFail VERSION_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail GIT_LATEST_TAG=`git describe --abbrev=0 --tags` && \
    exportOrFail GIT_COMMIT_SHA=`git rev-parse HEAD` && \
    exportOrFail JAEGER_VERSION=`grep jaeger= versions.txt | awk -F= '{print $2}'` && \
    go build -mod=mod -o ./jaeger-operator -trimpath -ldflags "-s -w -X ${VERSION_PKG}.version=${GIT_LATEST_TAG} -X ${VERSION_PKG}.buildDate=${VERSION_DATE} -X ${VERSION_PKG}.defaultJaeger=${JAEGER_VERSION}"

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:c38cc770631788157f8ea989df65ff30359c9f8af3246fef244b32caed9d5862
WORKDIR /

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install openssl -y && \
    microdnf clean all

RUN mkdir /licenses
COPY jaeger-operator/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger-operator/jaeger-operator /usr/bin/jaeger-operator
COPY --from=builder /opt/app-root/src/jaeger-operator/scripts/cert_generation.sh /scripts/cert_generation.sh

# required for /scripts/cert_generation.sh
RUN mkdir /tmp/_working_dir && chmod go+w /tmp/_working_dir

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger-operator"]

LABEL com.redhat.component="jaeger-operator-container" \
      name="rhosdt/jaeger-rhel8-operator" \
      summary="Jaeger Operator" \
      description="Operator for the Jaeger" \
      io.k8s.description="Operator for the Jaeger." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Operator"
