FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22@sha256:414352c89e06f25f79b4927328504edcdbfe676cd9596b44afff2eb4117c17e0 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY jaeger jaeger
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/jaegertracing/jaeger/pkg/version" && \
    exportOrFail VERSION_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail GIT_LATEST_TAG=`git describe --abbrev=0 --tags` && \
    exportOrFail GIT_COMMIT_SHA=`git rev-parse HEAD` && \
    go build -C ./cmd/collector -mod=mod -o ./jaeger -trimpath -ldflags "-s -w -X ${VERSION_PKG}.commitSHA=${GIT_COMMIT_SHA} -X ${VERSION_PKG}.latestVersion=${GIT_LATEST_TAG} -X ${VERSION_PKG}.date=${VERSION_DATE}"

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:c38cc770631788157f8ea989df65ff30359c9f8af3246fef244b32caed9d5862
WORKDIR /

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger/cmd/collector/jaeger /usr/bin/jaeger

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL com.redhat.component="jaeger-collector-container" \
      name="rhosdt/jaeger-collector-rhel8" \
      summary="Jaeger Collector" \
      description="Collector for the distributed tracing system" \
      io.k8s.description="Collector for the distributed tracing system." \
      io.openshift.expose-services="4317:otlp,4318:http,9411:zipkin" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Collector"
