FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22@sha256:99a63fb1eab333048e7f029dfacfe1054fc08b123b093e66a91ded52a908f781 as builder

WORKDIR /opt/app-root/src
USER root

COPY jaeger-operator .
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger-operator/LICENSE /licenses/

RUN export VERSION_PKG="github.com/jaegertracing/jaeger-operator/pkg/version" && \
  export VERSION_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
  export GIT_LATEST_TAG=`git describe --abbrev=0 --tags` && echo $GIT_LATEST_TAG && \
  export GIT_COMMIT_SHA=`git rev-parse HEAD` && echo $GIT_COMMIT_SHA && \
  export JAEGER_VERSION=`grep jaeger= versions.txt | awk -F= '{print $2}'` && echo $JAEGER_VERSION && \
  go build -mod=mod -o ./jaeger-operator -trimpath -ldflags "-s -w -X ${VERSION_PKG}.version=${GIT_LATEST_TAG} -X ${VERSION_PKG}.buildDate=${VERSION_DATE} -X ${VERSION_PKG}.defaultJaeger=${JAEGER_VERSION}"

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:c12e67af6a7e15113d76bc72f10bef2045c026c71ec8b7124c8a075458188a83
WORKDIR /

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install openssl -y && \
    microdnf clean all

RUN mkdir /licenses
COPY jaeger-operator/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger-operator /usr/bin/jaeger-operator

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger-operator"]

LABEL com.redhat.component="jaeger-operator-container" \
      name="rhosdt/jaeger-rhel8-operator" \
      summary="Jaeger Operator" \
      description="Operator for the Jaeger" \
      io.k8s.description="Operator for the Jaeger." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Operator"
