FROM registry.redhat.io/ubi9/ubi:latest@sha256:53d6c19d664f4f418ce5c823d3a33dbb562a2550ea249cf07ef10aa063ace38f as builder

USER root
WORKDIR /

RUN mkdir /licenses
COPY jaeger-operator/LICENSE /licenses/.

RUN dnf install -y python3 python3-ruamel-yaml-clib python3-ruamel-yaml patch

COPY bundle-patch .
COPY jaeger-operator/bundle/manifests /manifests/
COPY jaeger-operator/bundle/metadata /metadata/

RUN ls /manifests -al
RUN ls /metadata -al

# stage - registry.stage.redhat.io, prod - registry.redhat.io
ARG REGISTRY=quay.io/redhat-user-workloads

RUN ./update_bundle.sh && cat /manifests/jaeger-operator.clusterserviceversion.yaml /metadata/annotations.yaml

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:c38cc770631788157f8ea989df65ff30359c9f8af3246fef244b32caed9d5862

WORKDIR /
RUN mkdir /licenses
COPY jaeger-operator/LICENSE /licenses/.

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=jaeger-product
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.29.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL release="1.62.0-2" \
      version="1.62.0-2" \
      com.redhat.openshift.versions=v4.12 \
      name="rhosdt/jaeger-operator-bundle" \
      distribution-scope="public" \
      description="Bundle for Jaeger operator" \
      io.k8s.description="Bundle for Jaeger operator." \
      # TODO check if this is correct
      com.redhat.component="rhosdt" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Operator Bundle" \
      url="https://github.com/jaegertracing/jaeger-operator" \
      vendor="Red Hat, Inc." \
      summary="Jaeger operator bundle" \
      maintainer="support@redhat.com"

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY jaeger-operator/bundle/tests/scorecard /tests/scorecard/

ARG USER_UID=1001
USER ${USER_UID}
