FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22@sha256:99a63fb1eab333048e7f029dfacfe1054fc08b123b093e66a91ded52a908f781 as builder

WORKDIR /opt/app-root/src
USER root

COPY jaeger .
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/

RUN go build -C ./cmd/es-rollover -mod=mod -o ./jaeger -trimpath -ldflags "-s -w"


FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:c12e67af6a7e15113d76bc72f10bef2045c026c71ec8b7124c8a075458188a83
WORKDIR /

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/cmd/es-rollover/jaeger /usr/bin/jaeger

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL com.redhat.component="jaeger-es-rollover-container" \
      name="rhosdt/jaeger-es-rollover-rhel8" \
      summary="Jaeger ES rollover" \
      description="Index rollover for the distributed tracing system" \
      io.k8s.description="Index rollover for the distributed tracing system." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger ES rollover"
