FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:775e4b730b574841b34da2432afda83ef513aa3a0a7f9ffbe1e7cdea7e917012 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY jaeger jaeger
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger

RUN go build -C ./cmd/es-index-cleaner -mod=mod -o ./jaeger -trimpath -ldflags "-s -w"


FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:89f2c9794a3357a8463e3acc4dad45075b1a9a63ae05d4a493dd1451625f2222
WORKDIR /

# For installing RPM updates from lock file
RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf clean all

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger/cmd/es-index-cleaner/jaeger /usr/bin/jaeger

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL com.redhat.component="jaeger-es-index-cleaner-container" \
      name="rhosdt/jaeger-es-index-cleaner-rhel8" \
      summary="Jaeger ES index cleaner" \
      description="Index cleaner for the distributed tracing system" \
      io.k8s.description="Index cleaner for the distributed tracing system." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger ES index cleaner"
