apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: opentelemetry-operator-idms
spec:
  imageDigestMirrors:
  - source: registry.redhat.io/rhosdt/jaeger-rhel8-operator
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-operator
  - source: registry.redhat.io/rhosdt/jaeger-collector-rhel8
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-collector
  - source: registry.redhat.io/rhosdt/jaeger-query-rhel8
    mirrors:
       - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-query
  - source: registry.redhat.io/rhosdt/jaeger-agent-rhel8
    mirrors:
       - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-agent
  - source: registry.redhat.io/rhosdt/jaeger-ingester-rhel8
    mirrors:
       - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-ingester
  - source: registry.redhat.io/rhosdt/jaeger-all-in-one-rhel8
    mirrors:
       - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-all-in-one
  - source: registry.redhat.io/rhosdt/jaeger-es-index-cleaner-rhel8
    mirrors:
       - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-es-index-cleaner
  - source: registry.redhat.io/rhosdt/jaeger-es-rollover-rhel8
    mirrors:
       - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-es-rollover
  - source: registry.redhat.io/rhosdt/jaeger-operator-bundle
    mirrors:
       - quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-bundle